"""Initial database schema

Revision ID: 001
Revises:
Create Date: 2024-01-01 00:00:00.000000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # users 表
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("username", sa.String(50), nullable=False),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("display_name", sa.String(100), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("oauth_provider", sa.String(20), nullable=False),
        sa.Column("oauth_id", sa.String(100), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("oauth_provider", "oauth_id"),
    )
    op.create_index("idx_users_oauth", "users", ["oauth_provider", "oauth_id"])

    # teams 表
    op.create_table(
        "teams",
        sa.Column("id", postgresql.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("slug", sa.String(50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("external_dept_id", sa.String(100), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )

    # team_members 表
    op.create_table(
        "team_members",
        sa.Column("team_id", postgresql.UUID(), nullable=False),
        sa.Column("user_id", postgresql.UUID(), nullable=False),
        sa.Column("role", sa.String(20), server_default="member", nullable=False),
        sa.Column("joined_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "user_id"),
    )
    op.create_index("idx_team_members_user", "team_members", ["user_id"])

    # packages 表
    op.create_table(
        "packages",
        sa.Column("id", postgresql.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("scope", sa.String(50), nullable=False),
        sa.Column("full_name", sa.String(150), sa.Computed("scope || '/' || name", persisted=True), nullable=True),
        sa.Column("type", sa.String(10), nullable=False),
        sa.Column("owner_id", postgresql.UUID(), nullable=False),
        sa.Column("owner_type", sa.String(10), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("license", sa.String(50), server_default="MIT", nullable=True),
        sa.Column("repository", sa.Text(), nullable=True),
        sa.Column("homepage", sa.Text(), nullable=True),
        sa.Column("visibility", sa.String(10), server_default="public", nullable=True),
        sa.Column("downloads_count", sa.BigInteger(), server_default="0", nullable=True),
        sa.Column("latest_version", sa.String(50), nullable=True),
        sa.Column("tags", postgresql.JSONB(), server_default="[]", nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "name"),
    )
    op.create_index("idx_packages_full_name", "packages", ["full_name"])
    op.create_index("idx_packages_type", "packages", ["type"])
    op.create_index("idx_packages_owner", "packages", ["owner_id", "owner_type"])
    op.create_index("idx_packages_downloads", "packages", [sa.text("downloads_count DESC")])
    op.create_index("idx_packages_tags", "packages", ["tags"], postgresql_using="gin")
    op.create_index("idx_packages_deleted", "packages", ["deleted_at"], postgresql_where=sa.text("deleted_at IS NULL"))

    # versions 表
    op.create_table(
        "versions",
        sa.Column("id", postgresql.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("package_id", postgresql.UUID(), nullable=True),
        sa.Column("version", sa.String(50), nullable=False),
        sa.Column("manifest", postgresql.JSONB(), nullable=False),
        sa.Column("tarball_hash", sa.String(64), nullable=False),
        sa.Column("tarball_size", sa.BigInteger(), nullable=False),
        sa.Column("tarball_path", sa.String(500), nullable=False),
        sa.Column("dependencies", postgresql.JSONB(), server_default="{}", nullable=True),
        sa.Column("published_by", postgresql.UUID(), nullable=True),
        sa.Column("published_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deprecated", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("yanked", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("tag", sa.String(50), nullable=True),
        sa.ForeignKeyConstraint(["package_id"], ["packages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["published_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("package_id", "version"),
    )
    op.create_index("idx_versions_package", "versions", ["package_id", sa.text("version DESC")])

    # downloads 表
    op.create_table(
        "downloads",
        sa.Column("id", postgresql.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("package_id", postgresql.UUID(), nullable=True),
        sa.Column("version_id", postgresql.UUID(), nullable=True),
        sa.Column("user_id", postgresql.UUID(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("downloaded_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["package_id"], ["packages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["version_id"], ["versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_downloads_package", "downloads", ["package_id", "downloaded_at"])
    op.create_index("idx_downloads_version", "downloads", ["version_id"])

    # api_keys 表
    op.create_table(
        "api_keys",
        sa.Column("id", postgresql.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", postgresql.UUID(), nullable=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("key_hash", sa.String(128), nullable=False),
        sa.Column("key_prefix", sa.String(10), nullable=False),
        sa.Column("permissions", postgresql.JSONB(), server_default='["read", "write"]', nullable=True),
        sa.Column("last_used_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index("idx_api_keys_user", "api_keys", ["user_id"])
    op.create_index("idx_api_keys_hash", "api_keys", ["key_hash"])

    # reviews 表
    op.create_table(
        "reviews",
        sa.Column("id", postgresql.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("package_id", postgresql.UUID(), nullable=True),
        sa.Column("version_id", postgresql.UUID(), nullable=True),
        sa.Column("user_id", postgresql.UUID(), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["package_id"], ["packages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["version_id"], ["versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("package_id", "user_id"),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name="check_rating_range"),
    )
    op.create_index("idx_reviews_package", "reviews", ["package_id"])
    op.create_index("idx_reviews_rating", "reviews", ["package_id", "rating"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reviews")
    op.drop_table("api_keys")
    op.drop_table("downloads")
    op.drop_table("versions")
    op.drop_table("packages")
    op.drop_table("team_members")
    op.drop_table("teams")
    op.drop_table("users")
    # ### end Alembic commands ###
